export interface MSA{     
    accType:string,
    alternateMobile:string,
    attr1:string,
    attr2: string,
    attr3: string,
    attr4: any,
    baseLocation:string,
    addr1: string,
    addr2: string,
    addr3: string,
    latitude: any,
    longitude: any,
    pincodeId: any
    
    email:string,
    gstinNum:string,
    
    msaCustId: any,
   
    custName: string,
    descr: string,
    groupCode: string,
    id: any,
    mnthPotential: any,
    mobile: number,
    oldMsaCustId: any,
    opprId: any,
    opprName: string,
    originatingSrc: string,
    pan: string,
    phone: number,
    segment: string,
    sfdcAccId: string,
    sfdcMnthPotential3pl: any,
    sfdcMnthPotentialAir: any,
    sfdcMnthPotentialSurface: any,
    sfdcOpprId: string,
    sla: number,
    status: any,
    lookupVal:string,
    name: string,
    lkpConsigntypeId: number,
    panNum: number,
    gstNum: number,
    tanNum: number,
    mob: number,
    address: string,
    city: string,
    pincode: number,
    addrBookId:number,
    addrBook:any
    dealercode:string
}